### PR TITLE
Replace macro with generic array

### PR DESCRIPTION
**Pull request by zakcutner**

### CODE REVIEW

**Comment by marmeladema** [comment]
The benchmarks for short haystacks for `StrStrAVX2Searcher` have regressed significantly. However I am not sure this implementation is still relevant. I'd be ok to remove it prior to landing this PR.

On another hand, i'd be happy if you could take a look at the generated code for `strstr_avx2_rust` now that you pass a `impl Fn(*const u8, *const u8) -> bool` closure instead of function pointer. It should get monomorphized and inlined but i'd like to be sure or understand why its not.

**Comment by zakcutner** [comment]
@marmeladema I've simplified this PR a fair bit and I'm getting these results. It looks to me like there probably isn't a significant regression anymore.

```text
short_haystack/DynamicAvx2Searcher::search_in                                                                            
                        time:   [78.262 ms 78.450 ms 78.691 ms]
                        change: [-2.0954% -1.7250% -1.3269%] (p = 0.00 < 0.05)
                        Performance has improved.
long_haystack/DynamicAvx2Searcher::search_in                                                                            
                        time:   [35.440 ms 35.490 ms 35.556 ms]
                        change: [+0.6582% +0.9695% +1.2473%] (p = 0.00 < 0.05)
                        Change within noise threshold.
```

**Comment by marmeladema** [comment]
@zakcutner should this be closed now that #31 has landed?

**Comment by zakcutner** [comment]
@marmeladema Thanks, yep I'll close this

**Pull request closed without merging**
